#!/usr/bin/env node
/*
 * test_keyword_index.js  (standalone; auto-discovered by `npm run gauntlet`)
 *
 * Validates the big keyword fallback index shipped in bot/ExpenseBot_KEYWORDS.gs:
 *   - structural integrity (KFL_KW_BUCKETS + KFL_KW_INDEX well-formed)
 *   - the bot's _kfl_bigIndexLookup whole-word ngram lookup resolves every key
 *     back to its own bucket (round-trip), and rejects out-of-range buckets.
 *
 * SKIPS (exit 0) when ExpenseBot_KEYWORDS.gs is not present, so the gate stays
 * green before the data file is generated by bot/keywords/build_index.js.
 */
const fs = require('fs');
const path = require('path');

const KW = path.join(__dirname, '..', 'bot', 'ExpenseBot_KEYWORDS.gs');
let pass = 0, fail = 0;
function check(name, ok, extra) { if (ok) { pass++; } else { fail++; console.log('  FAIL ' + name + (extra ? ' :: ' + extra : '')); } }

if (!fs.existsSync(KW)) {
  console.log('test_keyword_index: SKIP — bot/ExpenseBot_KEYWORDS.gs not generated yet (run bot/keywords/build_index.js).');
  process.exit(0);
}

// Load the two data globals from the .gs (data-only file: var KFL_KW_BUCKETS=...; var KFL_KW_INDEX=...;).
const src = fs.readFileSync(KW, 'utf8');
const sandbox = {};
// eslint-disable-next-line no-new-func
new Function('__x', src + '\n__x.B = KFL_KW_BUCKETS; __x.I = KFL_KW_INDEX;')(sandbox);
const BUCKETS = sandbox.B, INDEX = sandbox.I;

// Mirror of bot _kfl_bigIndexLookup (kept in sync with ExpenseBot_FIXED.gs).
const PFX = ['וכשה', 'מהה', 'כשה', 'בהה', 'והה', 'ומ', 'ול', 'וב', 'וה', 'של', 'אצל', 'עם', 'כש', 'מה', 'בה', 'לה', 'כה', 'שה', 'ב', 'ל', 'מ', 'ה', 'ו', 'ש', 'כ'];
function bucketFor(phrase) {
  if (Object.prototype.hasOwnProperty.call(INDEX, phrase)) return INDEX[phrase];
  if (phrase.indexOf(' ') < 0 && /[֐-׿]/.test(phrase)) {
    for (const p of PFX) {
      if (phrase.length - p.length >= 3 && phrase.slice(0, p.length) === p) {
        const base = phrase.slice(p.length);
        if (Object.prototype.hasOwnProperty.call(INDEX, base)) return INDEX[base];
      }
    }
  }
  return undefined;
}
function lookup(text) {
  if (!INDEX || !BUCKETS || !text) return null;
  const words = String(text).toLowerCase().split(/[^0-9a-z֐-׿]+/).filter(Boolean);
  if (!words.length) return null;
  let best = null, bestLen = -1;
  const maxN = Math.min(4, words.length);
  for (let n = maxN; n >= 1; n--) {
    for (let s = 0; s + n <= words.length; s++) {
      const phrase = words.slice(s, s + n).join(' ');
      const bidx = bucketFor(phrase);
      if (bidx !== undefined && phrase.length > bestLen) {
        best = bidx; bestLen = phrase.length;
      }
    }
  }
  if (best == null) return null;
  const b = BUCKETS[best];
  return b ? { category: b[0], subcategory: b[1], isIncome: !!b[2] } : null;
}

// 1. structural integrity
check('KFL_KW_BUCKETS is a non-empty array', Array.isArray(BUCKETS) && BUCKETS.length > 0, 'len=' + (BUCKETS && BUCKETS.length));
check('KFL_KW_INDEX is an object', INDEX && typeof INDEX === 'object');
const keys = Object.keys(INDEX || {});
check('index has a substantial keyword count (>= 20000)', keys.length >= 20000, 'count=' + keys.length);
let badBucketShape = 0;
for (const b of BUCKETS) {
  if (!Array.isArray(b) || typeof b[0] !== 'string' || typeof b[1] !== 'string' || !b[0] || !b[1]) badBucketShape++;
}
check('every bucket is [category, subcategory, isIncome]', badBucketShape === 0, 'bad=' + badBucketShape);

// 2. every index value points at a real bucket
let outOfRange = 0;
for (const k of keys) { const v = INDEX[k]; if (!(v >= 0 && v < BUCKETS.length)) outOfRange++; }
check('no index value points out of bucket range', outOfRange === 0, 'oob=' + outOfRange);

// 3. round-trip: a deterministic sample of keys resolves back to its own bucket,
//    even embedded in surrounding text (whole-word match must still fire).
const stride = Math.max(1, Math.floor(keys.length / 400));
let rtFail = 0, sampled = 0;
for (let i = 0; i < keys.length; i += stride) {
  const k = keys[i];
  // skip keys with chars the tokenizer strips entirely (would not round-trip)
  if (!/[0-9a-z֐-׿]/.test(k)) continue;
  sampled++;
  const got = lookup('shilamti ' + k + ' 50');
  const want = BUCKETS[INDEX[k]];
  if (!got || got.category !== want[0] || got.subcategory !== want[1]) rtFail++;
}
check('round-trip lookup resolves sampled keys to their bucket', rtFail === 0, 'fail=' + rtFail + '/' + sampled);

// 3b. prefix recovery: a Hebrew base keyword with a "ב"/"ל" clitic prefix glued on
//     still resolves to the same bucket (the build step dropped such variants).
let pfxFail = 0, pfxSampled = 0;
for (let i = 0; i < keys.length && pfxSampled < 80; i += Math.max(1, Math.floor(keys.length / 200))) {
  const k = keys[i];
  if (k.indexOf(' ') >= 0 || !/^[֐-׿]{3,}$/.test(k)) continue; // single pure-Hebrew word, >=3 chars
  pfxSampled++;
  const got = bucketFor('ב' + k);
  if (got !== INDEX[k]) pfxFail++;
}
check('prefix-glued Hebrew word recovers its base bucket', pfxFail === 0, 'fail=' + pfxFail + '/' + pfxSampled);

// 4. lookup is null-safe on junk
check('lookup("") is null', lookup('') === null);
check('lookup of pure punctuation is null', lookup('!!! ??? ...') === null);

console.log('test_keyword_index: ' + pass + ' passed, ' + fail + ' failed  (index=' + keys.length + ' keywords, ' + BUCKETS.length + ' buckets)');
process.exit(fail ? 1 : 0);
