// lib/professions.js
//
// Israeli profession catalog for Kesefle.
// When a new user signs up via WhatsApp they pick (or are inferred into) one
// of these professions; the result drives:
//   - lib/sheet-writer.js : which rows the dashboard generates
//                           (income_subs / expense_subs become row labels)
//   - bot/ExpenseBot_FIXED.gs : classifier weights (keywords_boost is added
//                               to the user's per-profession lexicon so
//                               "בטון" routes a contractor's expense correctly)
//   - api/admin/* + start.html : the "I am a..." dropdown (uses he/en)
//
// SCHEMA -------------------------------------------------------------------
//   id              lowercase ASCII, no spaces. Stable forever — used as the
//                   key in the user's row in Sheet1. Don't rename.
//   he              Hebrew display name as a person in that profession would
//                   actually say it (e.g. "רואה חשבון", not "מומחה בחשבונאות")
//   en              English fallback for non-Hebrew users / admin tooling
//   category        one of the 10 buckets:
//                     construction | professional_services | healthcare |
//                     tech | retail_service | creative | education |
//                     logistics | agriculture | employee
//   vat             typical VAT status in Israel:
//                     'osek_morshe'  - turnover usually >~120k ILS/yr
//                     'osek_patur'   - turnover usually <~120k ILS/yr
//                     'employee'     - שכיר, no VAT registration
//                     'employer'     - חברה בע"מ / מעסיק עם דוחות מורכבים
//                   (this is the COMMON case, not the only legal case —
//                    the bot lets the user override during onboarding)
//   income_subs     5–10 Hebrew subcategory strings to appear on this user's
//                   income side of the dashboard. The first is the default.
//   expense_subs    5–12 Hebrew subcategory strings for the expense side.
//                   These become row labels in Sheet1 — keep them short
//                   (≤25 chars) so they render nicely RTL.
//   keywords_boost  10–20 *diagnostic* keywords (Hebrew + a few English)
//                   that should bias the classifier toward this profession's
//                   subcategory list. Avoid generic words ("כסף", "תשלום").
//   template_extras (optional) feature flags consumed by sheet-writer:
//                     'cash_flow_per_project' - per-project P&L tab
//                     'open_invoices'         - חשבוניות פתוחות tracker
//                     'mileage_log'           - km log + tax-deduction calc
//                     'inventory'             - stock-on-hand tab
//                     'tip_jar'               - daily tips column
//                     'gear_depreciation'     - equipment depreciation schedule
//                     'recurring_clients'     - retainer/subscription tracker
//                     'shift_log'             - hourly shift breakdown
//                     'commission_split'      - commission tracking
//                     'multi_currency'        - USD/EUR alongside ILS
//
// ADDING A NEW ENTRY -------------------------------------------------------
//   1. Pick an id no other entry uses.
//   2. Use the schema above. If your profession spans multiple categories
//      (e.g. a doctor who also has a clinic), pick the one that matches
//      MOST of their cash-flow reality.
//   3. Run `node -e "import('./lib/professions.js').then(m=>console.log(m.PROFESSIONS.length))"`
//      to sanity-check.
//   4. The dropdown auto-updates from PROFESSIONS — no UI edits needed.

export const PROFESSIONS = [
  // ============================================================
  // CONSTRUCTION (קבלנות, חשמל, אינסטלציה, שיפוצים)
  // ============================================================
  {
    id: 'general_contractor',
    he: 'קבלן בניין',
    en: 'General Contractor',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['תקבול מלקוח', 'מקדמה מלקוח', 'תשלום ביניים', 'תשלום סופי', 'החזר מע״מ', 'תוספות לחוזה'],
    expense_subs: ['חומרי בניין', 'פועלים', 'קבלני משנה', 'השכרת ציוד', 'דלק/רכב עבודה', 'ביטוח עסק', 'רואה חשבון', 'אגרות והיתרים', 'פינוי פסולת'],
    keywords_boost: ['בטון', 'גבס', 'בלוקים', 'טיט', 'אזמל', 'פיגומים', 'בנייה', 'יציקה', 'שלד', 'concrete', 'gypsum', 'rebar'],
    template_extras: ['cash_flow_per_project', 'open_invoices'],
  },
  {
    id: 'renovator',
    he: 'שיפוצניק',
    en: 'Home Renovator',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['תקבול מלקוח', 'מקדמה', 'תשלום סופי', 'תוספות בעבודה'],
    expense_subs: ['חומרי גמר', 'צבע', 'כלים', 'פועל יומי', 'דלק/רכב עבודה', 'פינוי פסולת', 'רואה חשבון', 'ביטוח עסק'],
    keywords_boost: ['צבע', 'טיח', 'פרקט', 'שיש', 'אריחים', 'שיפוץ', 'מטבח', 'אמבטיה', 'גבס', 'tile'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'electrician',
    he: 'חשמלאי',
    en: 'Electrician',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['קריאת שירות', 'התקנה חדשה', 'תיקון תקלה', 'בדיקת חשמל', 'אישור חשמלאי בודק'],
    expense_subs: ['חוטים וכבלים', 'מפסקים ושקעים', 'לוחות חשמל', 'כלי עבודה', 'דלק/רכב עבודה', 'ביטוח מקצועי', 'רישיון חשמלאי', 'רואה חשבון'],
    keywords_boost: ['ממסר', 'פחת', 'מפסק', 'שקע', 'לוח חשמל', 'כבל', 'תקלה חשמלית', 'הארקה', 'breaker', 'wire'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'plumber',
    he: 'אינסטלטור',
    en: 'Plumber',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['קריאת שירות', 'התקנת מערכת', 'תיקון נזילה', 'פתיחת סתימה', 'שירות חירום'],
    expense_subs: ['צנרת ופיטינגים', 'ברזים וסניטריה', 'כלי עבודה', 'אטמים וסיליקון', 'דלק/רכב עבודה', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['ברז', 'צינור', 'דוד שמש', 'אסלה', 'סתימה', 'נזילה', 'מחמם מים', 'אינסטלציה', 'pipe', 'leak'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'ac_technician',
    he: 'טכנאי מזגנים',
    en: 'AC Technician',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['התקנת מזגן', 'תיקון מזגן', 'ניקוי וטיפול', 'מילוי גז'],
    expense_subs: ['גז קירור', 'חלקי חילוף', 'כלי עבודה', 'ברגים וצינורות', 'דלק/רכב עבודה', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['מזגן', 'מעבה', 'גז קירור', 'מאייד', 'פריאון', 'אינוורטר', 'מיני מרכזי', 'r410', 'AC'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'carpenter',
    he: 'נגר',
    en: 'Carpenter',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['מטבח חדש', 'ארון בהזמנה', 'תיקון רהיט', 'התקנה באתר', 'מקדמה'],
    expense_subs: ['עץ ופורניר', 'ידיות וצירים', 'דבק וברגים', 'כלי נגרות', 'שכר נגר עוזר', 'שכירות סדנה', 'ביטוח עסק', 'רואה חשבון'],
    keywords_boost: ['עץ', 'סנדוויץ', 'פורניר', 'מסור', 'נגרות', 'מטבח', 'ארון', 'מדף', 'צירים', 'wood'],
    template_extras: ['cash_flow_per_project', 'inventory'],
  },
  {
    id: 'painter',
    he: 'צבעי',
    en: 'House Painter',
    category: 'construction',
    vat: 'osek_patur',
    income_subs: ['צביעת דירה', 'צביעה חיצונית', 'תיקוני צבע', 'מקדמה'],
    expense_subs: ['צבע', 'מברשות וגלילים', 'נייר מיסוך', 'סולמות', 'דלק/רכב עבודה', 'ביטוח עסק'],
    keywords_boost: ['צבע', 'גלילון', 'מברשת', 'טיח', 'שפכטל', 'לקה', 'תרסיס', 'paint', 'primer'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'mover',
    he: 'מוביל / סבל',
    en: 'Mover',
    category: 'construction',
    vat: 'osek_patur',
    income_subs: ['הובלת דירה', 'הובלה קטנה', 'אריזה', 'אחסון'],
    expense_subs: ['דלק', 'תחזוקת משאית', 'ביטוח רכב', 'פועלים יומיים', 'חומרי אריזה', 'חניות והיתרים'],
    keywords_boost: ['הובלה', 'אריזה', 'משאית', 'סבל', 'דירה', 'קרטונים', 'מעלית הובלה', 'moving'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'aluminum_installer',
    he: 'מתקין אלומיניום',
    en: 'Aluminum Installer',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['חלונות אלומיניום', 'דלת זכוכית', 'מקלחון', 'תיקון רשת', 'מקדמה'],
    expense_subs: ['פרופילי אלומיניום', 'זכוכית', 'אביזרים', 'אטמים', 'כלי עבודה', 'דלק/רכב עבודה', 'רואה חשבון'],
    keywords_boost: ['אלומיניום', 'חלון', 'תריס', 'מקלחון', 'זכוכית', 'רשת', 'פרופיל', 'aluminum', 'window'],
  },
  {
    id: 'tiler',
    he: 'רצף',
    en: 'Tiler',
    category: 'construction',
    vat: 'osek_morshe',
    income_subs: ['ריצוף דירה', 'חיפוי קירות', 'תיקוני ריצוף', 'מקדמה'],
    expense_subs: ['אריחים', 'דבק לאריחים', 'רובה', 'כלי חיתוך', 'פועל עוזר', 'דלק/רכב עבודה', 'ביטוח עסק'],
    keywords_boost: ['אריח', 'גרניט', 'פורצלן', 'דבק אריחים', 'רובה', 'ריצוף', 'קרמיקה', 'tile', 'grout'],
  },
  {
    id: 'landscaper',
    he: 'גנן',
    en: 'Landscaper',
    category: 'construction',
    vat: 'osek_patur',
    income_subs: ['תחזוקת גינה', 'גיזום', 'תכנון גינה', 'השקיה'],
    expense_subs: ['שתילים וצמחים', 'דשנים', 'כלי גינון', 'דלק/רכב עבודה', 'ביטוח עסק', 'פועלים'],
    keywords_boost: ['גינה', 'גיזום', 'דשא', 'השקיה', 'שתיל', 'דשן', 'עץ', 'משתלה', 'gardening'],
  },

  // ============================================================
  // PROFESSIONAL SERVICES (משפט, חשבונאות, ייעוץ, אדריכלות)
  // ============================================================
  {
    id: 'lawyer',
    he: 'עורך דין',
    en: 'Lawyer',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['שכר טרחה', 'מקדמה', 'אחוזים מתביעה', 'ייעוץ חד פעמי', 'ריטיינר חודשי', 'החזר הוצאות'],
    expense_subs: ['שכר דירה למשרד', 'מזכירות', 'תוכנות משפטיות', 'מאגרי פסיקה', 'אגרות בית משפט', 'לשכת עורכי הדין', 'ביטוח מקצועי', 'רואה חשבון', 'השתלמויות'],
    keywords_boost: ['אגרת בית משפט', 'נבו', 'תקדין', 'לשכת עוה״ד', 'תביעה', 'ייפוי כוח', 'הסכם', 'פסיקה', 'court', 'litigation'],
    template_extras: ['open_invoices', 'recurring_clients'],
  },
  {
    id: 'accountant',
    he: 'רואה חשבון',
    en: 'Accountant (CPA)',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['שכר טרחה חודשי', 'דו״ח שנתי', 'ליווי שוטף', 'חוות דעת', 'ייעוץ מס'],
    expense_subs: ['ביטוח מקצועי', 'תוכנות (חשבשבת/iCount)', 'מנוי לאתרי חקיקה', 'מועדון רואי חשבון', 'השתלמויות', 'שכ״ד למשרד', 'מזכירות'],
    keywords_boost: ['חשבשבת', 'icount', 'דוח שנתי', 'מע״מ', 'מס הכנסה', 'חשבונאות', 'מאזן', 'IFRS', 'CPA'],
    template_extras: ['recurring_clients', 'open_invoices'],
  },
  {
    id: 'bookkeeper',
    he: 'מנהלת חשבונות',
    en: 'Bookkeeper',
    category: 'professional_services',
    vat: 'osek_patur',
    income_subs: ['הנהלת חשבונות חודשית', 'דיווח מע״מ', 'דיווח ניכויים', 'הקמת תיק חדש'],
    expense_subs: ['תוכנות (חשבשבת/רמיניב)', 'השתלמויות', 'ביטוח מקצועי', 'מנוי לאתרי תקנות', 'מסך/מחשב', 'אינטרנט עסקי'],
    keywords_boost: ['רמיניב', 'חשבשבת', 'הנה״ח', 'ניכויים', 'דיווח מע״מ', 'ספרים', 'תלוש', 'bookkeeping'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'tax_advisor',
    he: 'יועץ מס',
    en: 'Tax Advisor',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['שכר טרחה', 'הגשת דו״ח שנתי', 'ייצוג מול רשויות', 'חוות דעת', 'ליווי שוטף'],
    expense_subs: ['ביטוח מקצועי', 'תוכנות יעוץ מס', 'מנוי לחקיקה', 'לשכת יועצי מס', 'השתלמויות', 'משרד/שכ״ד'],
    keywords_boost: ['רשות המסים', 'דוח שנתי', 'החזר מס', 'נקודות זיכוי', 'יועץ מס', 'מע״מ', 'ניכוי', 'tax'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'financial_advisor',
    he: 'יועץ פיננסי',
    en: 'Financial Advisor',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['ייעוץ אישי', 'תוכנית פיננסית', 'ליווי משפחה', 'הרצאה / סדנה', 'אחוז מנכסים בניהול'],
    expense_subs: ['רישיון פיננסי', 'ביטוח מקצועי', 'מנוי לבלומברג/CalcalistPro', 'CRM', 'שיווק דיגיטלי', 'רואה חשבון'],
    keywords_boost: ['בלומברג', 'תיק השקעות', 'קרן השתלמות', 'גמל', 'פנסיה', 'נדל״ן להשקעה', 'תכנון פיננסי', 'portfolio'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'insurance_agent',
    he: 'סוכן ביטוח',
    en: 'Insurance Agent',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['עמלות נפרעים', 'עמלות חדשים', 'בונוס חברת ביטוח', 'דמי טיפול שנתיים'],
    expense_subs: ['רישיון סוכן', 'ביטוח מקצועי', 'CRM סוכנים', 'שיווק לידים', 'דלק/רכב עבודה', 'משרד', 'מזכירות'],
    keywords_boost: ['פוליסה', 'עמלת ביטוח', 'הראל', 'מגדל', 'כלל', 'מנורה', 'איילון', 'פניקס', 'סוכן ביטוח', 'insurance'],
    template_extras: ['recurring_clients', 'commission_split'],
  },
  {
    id: 'real_estate_agent',
    he: 'מתווך נדל״ן',
    en: 'Real Estate Agent',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['דמי תיווך מכר', 'דמי תיווך שכירות', 'דמי תיווך מסחרי', 'בונוס'],
    expense_subs: ['פרסום בלוחות', 'יד2/מדלן', 'שילוט "למכירה"', 'דלק/רכב עבודה', 'רישיון תיווך', 'ביטוח מקצועי', 'CRM', 'משרד'],
    keywords_boost: ['יד2', 'מדלן', 'הומלס', 'תיווך', 'דירה למכירה', 'דירה להשכרה', 'רימקס', 'אנגלו סכסון', 'realestate'],
    template_extras: ['commission_split', 'recurring_clients'],
  },
  {
    id: 'architect',
    he: 'אדריכל',
    en: 'Architect',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['תכנון אדריכלי', 'תכנון פנים', 'הגשת היתר', 'פיקוח ביצוע', 'מקדמה'],
    expense_subs: ['רישיונות תוכנה (AutoCAD/Revit)', 'אגרות הגשה', 'הדפסות גדולות', 'אגודת האדריכלים', 'ביטוח מקצועי', 'משרד', 'מתמחה'],
    keywords_boost: ['autocad', 'revit', 'sketchup', 'תוכנית', 'היתר בנייה', 'תב״ע', 'אדריכלות', 'גרמושקה', 'architect'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'interior_designer',
    he: 'מעצב פנים',
    en: 'Interior Designer',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['תכנון פנים', 'ליווי שיפוץ', 'בחירת ריהוט', 'עמלת ספקים', 'מקדמה'],
    expense_subs: ['רישיונות תוכנה', 'דוגמאות חומרים', 'מנוי Pinterest/Houzz', 'צילום פרויקטים', 'משרד', 'דלק/רכב עבודה'],
    keywords_boost: ['עיצוב פנים', 'ריהוט', 'תאורה', 'טקסטיל', 'דוגמית', 'houzz', 'pinterest', 'mood board', 'designer'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'engineer_freelance',
    he: 'מהנדס פרילנס',
    en: 'Freelance Engineer',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['פרויקט הנדסי', 'חוות דעת', 'פיקוח', 'ייעוץ שעתי', 'מקדמה'],
    expense_subs: ['רישיונות תוכנה', 'אגודת המהנדסים', 'ביטוח מקצועי', 'השתלמויות', 'משרד/קוורקינג', 'דלק/רכב'],
    keywords_boost: ['הנדסה אזרחית', 'קונסטרוקטור', 'חישוב סטטי', 'תוכנית הנדסית', 'pe', 'engineering', 'mechanical'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'management_consultant',
    he: 'יועץ ארגוני',
    en: 'Management Consultant',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['ייעוץ שעתי', 'פרויקט אסטרטגי', 'ריטיינר חודשי', 'הרצאה', 'סדנה'],
    expense_subs: ['נסיעות עסקים', 'מנוי HBR/Statista', 'תוכנות (Slack/Notion/Miro)', 'שיווק LinkedIn', 'משרד/קוורקינג', 'רואה חשבון'],
    keywords_boost: ['אסטרטגיה', 'KPI', 'OKR', 'Lean', 'Six Sigma', 'תהליכי עבודה', 'יעוץ', 'consulting', 'transformation'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'translator',
    he: 'מתרגם',
    en: 'Translator',
    category: 'professional_services',
    vat: 'osek_patur',
    income_subs: ['תרגום מסמך', 'תרגום מילולי לשעה', 'עריכה לשונית', 'תרגום סימולטני', 'תרגום נוטריוני'],
    expense_subs: ['תוכנות CAT (Trados)', 'מנוי לקורפוס', 'מילונים', 'אגודת המתרגמים', 'אינטרנט עסקי', 'מחשב'],
    keywords_boost: ['תרגום', 'עריכה לשונית', 'נוטריוני', 'CAT tool', 'Trados', 'memoQ', 'translation', 'localization'],
  },
  {
    id: 'notary',
    he: 'נוטריון',
    en: 'Notary',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['אישור נוטריוני', 'תרגום נוטריוני', 'ייפוי כוח', 'תצהיר'],
    expense_subs: ['חותמת נוטריון', 'ספרי נוטריון', 'ביטוח מקצועי', 'אגרות', 'משרד', 'מזכירות'],
    keywords_boost: ['נוטריון', 'אישור נוטריוני', 'תצהיר', 'ייפוי כוח', 'אפוסטיל', 'notary', 'apostille'],
  },
  {
    id: 'private_investigator',
    he: 'חוקר פרטי',
    en: 'Private Investigator',
    category: 'professional_services',
    vat: 'osek_morshe',
    income_subs: ['חקירה לבלשי ביטוח', 'חקירה פרטית', 'מעקב', 'דוח מקיף'],
    expense_subs: ['רישיון חוקר', 'ציוד מעקב', 'דלק/רכב עבודה', 'ביטוח מקצועי', 'משרד', 'תוכנות מודיעין'],
    keywords_boost: ['חקירה', 'מעקב', 'גוגל ארץ', 'בלש', 'מודיעין עסקי', 'OSINT', 'private investigator'],
    template_extras: ['mileage_log'],
  },

  // ============================================================
  // HEALTHCARE (רופאים, אחיות, פסיכולוגים)
  // ============================================================
  {
    id: 'physician_employed',
    he: 'רופא בית חולים',
    en: 'Hospital Physician',
    category: 'healthcare',
    vat: 'employee',
    income_subs: ['משכורת', 'תורנות', 'שעות נוספות', 'תוספת ותק', 'מענק התמחות'],
    expense_subs: ['ביטוח מקצועי', 'הר״י', 'השתלמויות', 'כנסים', 'ספרות מקצועית', 'מנוי UpToDate'],
    keywords_boost: ['קופ״ח', 'הר״י', 'תורנות', 'התמחות', 'מומחיות', 'UpToDate', 'beilinson', 'ichilov', 'physician'],
  },
  {
    id: 'physician_private',
    he: 'רופא במרפאה פרטית',
    en: 'Private Practice Physician',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['ביקור פרטי', 'ייעוץ שני', 'חוות דעת', 'הסדר עם ביטוח', 'מקדמה לטיפול'],
    expense_subs: ['שכר דירה למרפאה', 'ציוד רפואי', 'מזכירות רפואית', 'ביטוח מקצועי', 'הר״י', 'השתלמויות', 'CRM רפואי', 'רואה חשבון'],
    keywords_boost: ['ייעוץ רפואי', 'מרפאה', 'מומחה', 'מכבי', 'כללית', 'מאוחדת', 'לאומית', 'UpToDate', 'clinic'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'dentist',
    he: 'רופא שיניים',
    en: 'Dentist',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['בדיקה תקופתית', 'סתימה', 'כתר', 'יישור שיניים', 'שתל', 'הסדר ביטוח'],
    expense_subs: ['חומרים דנטליים', 'מעבדת שיניים', 'שכר דירה למרפאה', 'סייעת רפואית', 'תחזוקת ציוד דנטלי', 'הסתדרות רופאי שיניים', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['סתימה', 'כתר', 'שתל', 'אינווייזליין', 'יישור', 'הסתדרות רופ״ש', 'אזוטרפיה', 'dental', 'implant'],
    template_extras: ['recurring_clients', 'inventory'],
  },
  {
    id: 'nurse',
    he: 'אחות',
    en: 'Nurse',
    category: 'healthcare',
    vat: 'employee',
    income_subs: ['משכורת', 'תורנות', 'שעות נוספות', 'תוספת לילה', 'תוספת ותק'],
    expense_subs: ['ביטוח מקצועי', 'הסתדרות האחיות', 'נעלי עבודה', 'מדים', 'השתלמויות'],
    keywords_boost: ['קופ״ח', 'בית חולים', 'תורנות', 'משמרת לילה', 'הסתדרות אחיות', 'סיעוד', 'nurse', 'shift'],
  },
  {
    id: 'physiotherapist',
    he: 'פיזיותרפיסט',
    en: 'Physiotherapist',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['טיפול פרטי', 'חבילת טיפולים', 'הסדר ביטוח', 'ביקור בית', 'הרצאה לארגון'],
    expense_subs: ['ציוד פיזיותרפיה', 'שמן עיסוי', 'שכר דירה לקליניקה', 'הסתדרות פיזיותרפיסטים', 'ביטוח מקצועי', 'השתלמויות', 'רואה חשבון'],
    keywords_boost: ['פיזיותרפיה', 'גירוי חשמלי', 'דיקור יבש', 'יוגה רפואית', 'קליניקה', 'גב תחתון', 'physio', 'rehab'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'psychologist',
    he: 'פסיכולוג',
    en: 'Psychologist',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['פגישה פרטית', 'אבחון פסיכודיאגנוסטי', 'חבילת פגישות', 'ייעוץ למשפחה', 'הדרכה'],
    expense_subs: ['שכ״ד לקליניקה', 'מבחנים פסיכולוגיים', 'הסתדרות הפסיכולוגים', 'הדרכה אישית', 'ביטוח מקצועי', 'השתלמויות', 'רואה חשבון'],
    keywords_boost: ['פסיכותרפיה', 'CBT', 'דינמי', 'הדרכה', 'WAIS', 'אבחון', 'קליניקה', 'הסתדרות הפסיכולוגים', 'therapy'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'psychiatrist',
    he: 'פסיכיאטר',
    en: 'Psychiatrist',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['בדיקה ראשונית', 'מעקב תרופתי', 'חוות דעת משפטית', 'הסדר ביטוח'],
    expense_subs: ['שכ״ד לקליניקה', 'מזכירות', 'ביטוח מקצועי', 'הר״י', 'מנוי UpToDate', 'השתלמויות'],
    keywords_boost: ['פסיכיאטריה', 'תרופה', 'מרשם', 'הפרעה דו-קוטבית', 'דיכאון', 'חרדה', 'ADHD', 'psychiatrist'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'social_worker',
    he: 'עובד סוציאלי',
    en: 'Social Worker',
    category: 'healthcare',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'תוספת מאמצים', 'מענק חתימה'],
    expense_subs: ['ביטוח מקצועי', 'איגוד העו״ס', 'השתלמויות', 'נסיעות תפקיד', 'מנוי לכתבי עת'],
    keywords_boost: ['רווחה', 'איגוד עו״ס', 'בית חולים', 'שירותי רווחה', 'תיק', 'איתור', 'social worker'],
  },
  {
    id: 'pharmacist',
    he: 'רוקח',
    en: 'Pharmacist',
    category: 'healthcare',
    vat: 'employee',
    income_subs: ['משכורת', 'משמרת ערב', 'תוספת רוקח אחראי', 'בונוס מכירות'],
    expense_subs: ['רישיון רוקח', 'איגוד הרוקחים', 'השתלמויות', 'נסיעות לעבודה'],
    keywords_boost: ['בית מרקחת', 'מרשם', 'תרופה', 'סופר פארם', 'ניו-פארם', 'רוקח אחראי', 'pharmacy', 'prescription'],
  },
  {
    id: 'pharmacy_owner',
    he: 'בעל בית מרקחת',
    en: 'Pharmacy Owner',
    category: 'healthcare',
    vat: 'employer',
    income_subs: ['מכירות תרופות מרשם', 'מכירות OTC', 'קוסמטיקה ופארמה', 'הסדר קופ״ח'],
    expense_subs: ['רכישת תרופות', 'משכורות עובדים', 'שכ״ד', 'תוכנת בית מרקחת', 'ביטוח עסק', 'אגרות רישוי', 'רואה חשבון'],
    keywords_boost: ['בית מרקחת', 'תרופות', 'OTC', 'קוסמטיקה', 'משלוח תרופות', 'רוקחות', 'pharmacy owner'],
    template_extras: ['inventory', 'open_invoices'],
  },
  {
    id: 'optometrist',
    he: 'אופטומטריסט',
    en: 'Optometrist',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['בדיקת ראייה', 'מכירת משקפיים', 'עדשות מגע', 'תיקון משקפיים', 'הסדר קופ״ח'],
    expense_subs: ['מסגרות ועדשות', 'ציוד אופטי', 'שכ״ד', 'איגוד האופטומטריסטים', 'ביטוח עסק', 'רואה חשבון'],
    keywords_boost: ['משקפיים', 'עדשות מגע', 'בדיקת ראייה', 'מספר', 'אסטיגמט', 'אופטיקנה', 'optometry', 'lens'],
    template_extras: ['inventory'],
  },
  {
    id: 'veterinarian',
    he: 'וטרינר',
    en: 'Veterinarian',
    category: 'healthcare',
    vat: 'osek_morshe',
    income_subs: ['בדיקה כללית', 'חיסון', 'ניתוח', 'אשפוז', 'ביקור בית', 'הסדר ביטוח חיות'],
    expense_subs: ['תרופות וטרינריות', 'ציוד וטרינרי', 'שכ״ד למרפאה', 'מזכירות', 'הסתדרות הוטרינרים', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['וטרינר', 'חיסון', 'עיקור', 'סירוס', 'כלב', 'חתול', 'מרפאת חיות', 'vet', 'animal'],
    template_extras: ['recurring_clients', 'inventory'],
  },
  {
    id: 'dietitian',
    he: 'דיאטנית',
    en: 'Dietitian',
    category: 'healthcare',
    vat: 'osek_patur',
    income_subs: ['פגישה ראשונה', 'פגישת מעקב', 'חבילת ליווי', 'תוכנית תזונה', 'סדנה'],
    expense_subs: ['רישיון תזונאית', 'מאזניים מקצועיים', 'תוכנת תפריטים', 'הסתדרות הדיאטנים', 'השתלמויות', 'קליניקה'],
    keywords_boost: ['תזונה', 'דיאטה', 'BMI', 'תפריט', 'הרזיה', 'תוסף', 'דיאטנית', 'dietitian', 'nutrition'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'alternative_therapist',
    he: 'מטפל ברפואה משלימה',
    en: 'Alternative Therapist',
    category: 'healthcare',
    vat: 'osek_patur',
    income_subs: ['טיפול עיסוי', 'דיקור סיני', 'רפלקסולוגיה', 'ריקי', 'חבילת טיפולים'],
    expense_subs: ['שמני עיסוי', 'מחטי דיקור', 'שכ״ד לקליניקה', 'השתלמויות', 'ביטוח מקצועי'],
    keywords_boost: ['רפואה משלימה', 'דיקור', 'שיאצו', 'רפלקסולוגיה', 'ריקי', 'הומאופתיה', 'massage', 'acupuncture'],
    template_extras: ['recurring_clients'],
  },

  // ============================================================
  // TECH (מפתחים, UX, DevOps, סייבר)
  // ============================================================
  {
    id: 'software_developer_employed',
    he: 'מפתח תוכנה (שכיר)',
    en: 'Software Developer (Employee)',
    category: 'tech',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס שנתי', 'אופציות (RSU)', 'מענק חתימה', 'תוספת תורנות'],
    expense_subs: ['ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'נסיעות לעבודה', 'אינטרנט ביתי', 'קורסים מקצועיים'],
    keywords_boost: ['github', 'jira', 'AWS', 'react', 'typescript', 'docker', 'k8s', 'startup', 'הייטק', 'developer'],
  },
  {
    id: 'software_developer_freelance',
    he: 'מפתח תוכנה פרילנס',
    en: 'Freelance Developer',
    category: 'tech',
    vat: 'osek_morshe',
    income_subs: ['פרויקט שעתי', 'פרויקט קבוע', 'ריטיינר חודשי', 'מקדמה', 'תשלום במטבע חוץ'],
    expense_subs: ['מנוי GitHub/Cursor', 'AWS/GCP', 'מחשב חדש', 'מסכים וציוד', 'מנוי JetBrains', 'אינטרנט עסקי', 'WeWork/קוורקינג', 'רואה חשבון'],
    keywords_boost: ['github copilot', 'AWS', 'vercel', 'cursor', 'react', 'next.js', 'kubernetes', 'devops', 'freelance dev'],
    template_extras: ['open_invoices', 'multi_currency'],
  },
  {
    id: 'ux_designer',
    he: 'מעצב UX/UI',
    en: 'UX/UI Designer',
    category: 'tech',
    vat: 'osek_morshe',
    income_subs: ['פרויקט עיצוב', 'פרילנס שעתי', 'ריטיינר', 'אודיט UX', 'הרצאה'],
    expense_subs: ['Figma Pro', 'Adobe Creative Cloud', 'מנוי Maze/UserTesting', 'גופנים', 'תמונות סטוק', 'מחשב/מסך', 'קוורקינג'],
    keywords_boost: ['figma', 'sketch', 'adobe xd', 'prototype', 'wireframe', 'user research', 'UX', 'UI', 'design system'],
    template_extras: ['multi_currency'],
  },
  {
    id: 'product_manager',
    he: 'מנהל מוצר',
    en: 'Product Manager',
    category: 'tech',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס שנתי', 'אופציות (RSU)', 'מענק חתימה'],
    expense_subs: ['ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'נסיעות לעבודה', 'קורסים', 'ספרים מקצועיים', 'כנסים'],
    keywords_boost: ['jira', 'confluence', 'notion', 'roadmap', 'OKR', 'sprint', 'product manager', 'PRD', 'PM'],
  },
  {
    id: 'devops_engineer',
    he: 'מהנדס DevOps',
    en: 'DevOps Engineer',
    category: 'tech',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס', 'אופציות', 'תוספת תורנות (on-call)'],
    expense_subs: ['ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'הסמכות (AWS/k8s)', 'מעבדה ביתית', 'קורסים'],
    keywords_boost: ['kubernetes', 'terraform', 'ansible', 'docker', 'jenkins', 'ci/cd', 'on-call', 'devops', 'sre'],
  },
  {
    id: 'cybersecurity',
    he: 'מומחה סייבר',
    en: 'Cybersecurity Specialist',
    category: 'tech',
    vat: 'osek_morshe',
    income_subs: ['מבדק חדירה', 'ייעוץ אבטחה', 'ריטיינר', 'תגובה לאירוע', 'הרצאה / קורס'],
    expense_subs: ['כלי פנטסט (Burp/Kali)', 'הסמכות (OSCP/CISSP)', 'מעבדה וירטואלית', 'מחשב', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['pentest', 'burp suite', 'kali', 'OSCP', 'CISSP', 'SOC', 'CISO', 'בעלון אבטחה', 'cybersecurity'],
    template_extras: ['multi_currency'],
  },
  {
    id: 'data_scientist',
    he: 'מדען נתונים',
    en: 'Data Scientist',
    category: 'tech',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס שנתי', 'אופציות (RSU)'],
    expense_subs: ['ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'נסיעות לעבודה', 'קורסי ML', 'כנסים'],
    keywords_boost: ['python', 'tensorflow', 'pytorch', 'kaggle', 'jupyter', 'pandas', 'machine learning', 'LLM', 'data scientist'],
  },
  {
    id: 'qa_engineer',
    he: 'בודק תוכנה (QA)',
    en: 'QA Engineer',
    category: 'tech',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'בונוס', 'תוספת לילה'],
    expense_subs: ['ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'נסיעות לעבודה', 'קורסי אוטומציה'],
    keywords_boost: ['selenium', 'cypress', 'jest', 'jira', 'bugzilla', 'test plan', 'automation', 'QA', 'בדיקות'],
  },
  {
    id: 'it_support',
    he: 'תומך IT',
    en: 'IT Support',
    category: 'tech',
    vat: 'osek_patur',
    income_subs: ['קריאת שירות', 'תחזוקה חודשית', 'התקנת רשת', 'גיבוי וענן', 'תיקון מחשב'],
    expense_subs: ['חלפים וכלים', 'דלק/רכב עבודה', 'תוכנות (TeamViewer/Acronis)', 'ביטוח מקצועי', 'רואה חשבון'],
    keywords_boost: ['windows', 'ראוטר', 'wifi', 'גיבוי', 'שרת', 'תקלת מחשב', 'הגדרת רשת', 'teamviewer', 'IT support'],
    template_extras: ['recurring_clients', 'mileage_log'],
  },

  // ============================================================
  // RETAIL & SERVICE (קופאים, מלצרים, ברמנים, ספרים, נהגים)
  // ============================================================
  {
    id: 'cashier',
    he: 'קופאי',
    en: 'Cashier',
    category: 'retail_service',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'טיפים', 'החזרי נסיעות', 'תוספת חג'],
    expense_subs: ['נסיעות לעבודה', 'אוכל בעבודה', 'מדים', 'ביטוח רפואי משלים'],
    keywords_boost: ['קופה', 'משמרת', 'סופר', 'רמי לוי', 'שופרסל', 'יינות ביתן', 'cashier', 'shift'],
  },
  {
    id: 'waiter',
    he: 'מלצר',
    en: 'Waiter',
    category: 'retail_service',
    vat: 'employee',
    income_subs: ['שכר שעתי', 'טיפים', 'משמרת ארוכה', 'בונוס סופ״ש'],
    expense_subs: ['נסיעות לעבודה', 'בגדי עבודה', 'נעלי עבודה', 'אוכל לפני משמרת'],
    keywords_boost: ['מלצרות', 'טיפ', 'משמרת', 'מסעדה', 'ברנש', 'POS', 'waiter', 'tips'],
    template_extras: ['tip_jar', 'shift_log'],
  },
  {
    id: 'bartender',
    he: 'ברמן',
    en: 'Bartender',
    category: 'retail_service',
    vat: 'employee',
    income_subs: ['שכר שעתי', 'טיפים', 'משמרת לילה', 'בונוס סופ״ש'],
    expense_subs: ['נסיעות לעבודה', 'בגדי עבודה', 'קורסי מיקסולוגיה'],
    keywords_boost: ['ברמן', 'קוקטייל', 'מיקסולוגיה', 'בר', 'משמרת לילה', 'טיפ', 'bartender', 'cocktail'],
    template_extras: ['tip_jar', 'shift_log'],
  },
  {
    id: 'restaurant_owner',
    he: 'בעל מסעדה',
    en: 'Restaurant Owner',
    category: 'retail_service',
    vat: 'employer',
    income_subs: ['מכירות באולם', 'משלוחים (Wolt/10bis)', 'אירועים פרטיים', 'מכירות לעסקים'],
    expense_subs: ['חומרי גלם', 'משכורות עובדים', 'שכ״ד', 'חשמל ומים', 'תוכנת POS', 'עמלות 10bis/Wolt', 'ביטוח עסק', 'אגרת רישוי עסק', 'רואה חשבון'],
    keywords_boost: ['מסעדה', '10bis', 'wolt', 'cibus', 'מטבח', 'שף', 'POS', 'תפריט', 'restaurant'],
    template_extras: ['inventory', 'open_invoices'],
  },
  {
    id: 'cafe_owner',
    he: 'בעל בית קפה',
    en: 'Cafe Owner',
    category: 'retail_service',
    vat: 'employer',
    income_subs: ['מכירות באולם', 'מכירות Takeaway', 'משלוחים', 'אירועים', 'הסדרי קייטרינג'],
    expense_subs: ['פולי קפה', 'חלב ומאפים', 'משכורות', 'שכ״ד', 'תחזוקת מכונת קפה', 'חשמל ומים', 'אריזות', 'ביטוח עסק'],
    keywords_boost: ['קפה', 'אספרסו', 'בריסטה', 'מאפה', 'קרואסון', 'פולי קפה', 'cafe', 'espresso'],
    template_extras: ['inventory', 'shift_log'],
  },
  {
    id: 'hairstylist',
    he: 'ספר/ית',
    en: 'Hairstylist',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['תספורת', 'צבע', 'החלקה', 'תיסרוקת ערב', 'טיפים'],
    expense_subs: ['חומרי צבע', 'מספריים ומברשות', 'שכ״ד למספרה', 'מוצרי קוסמטיקה למכירה', 'חשמל ומים', 'ביטוח עסק'],
    keywords_boost: ['תספורת', 'צבע שיער', 'מספרה', 'החלקה', 'פן', 'גוונים', 'בלונד', 'hair', 'stylist'],
    template_extras: ['recurring_clients', 'tip_jar'],
  },
  {
    id: 'barber',
    he: 'ברבר',
    en: 'Barber',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['תספורת גברים', 'זקן', 'גילוח', 'טיפים', 'מנוי חודשי'],
    expense_subs: ['מכונות וסכינים', 'שכ״ד לברברשופ', 'מוצרי טיפוח גברים', 'חשמל ומים', 'ביטוח עסק'],
    keywords_boost: ['ברבר', 'תספורת גברים', 'זקן', 'גילוח חם', 'fade', 'barbershop', 'משחה'],
    template_extras: ['recurring_clients', 'tip_jar'],
  },
  {
    id: 'makeup_artist',
    he: 'מאפרת',
    en: 'Makeup Artist',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['איפור כלות', 'איפור ערב', 'איפור צילום', 'סדנת איפור', 'מקדמה'],
    expense_subs: ['מוצרי איפור', 'מברשות', 'תיק נשיאה', 'שיווק אינסטגרם', 'דלק/רכב עבודה'],
    keywords_boost: ['איפור', 'כלה', 'מאפרת', 'mac', 'nars', 'huda', 'אייליינר', 'makeup', 'bridal'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'manicurist',
    he: 'מניקוריסטית',
    en: 'Manicurist',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['מניקור', 'פדיקור', 'ג׳ל / לק ג׳ל', 'בניית ציפורניים', 'טיפים'],
    expense_subs: ['לק וג׳ל', 'מנורת UV', 'כלים סטריליים', 'שכ״ד / פינה במכון', 'חומרי חיטוי'],
    keywords_boost: ['מניקור', 'פדיקור', 'ג׳ל', 'לק', 'ציפורניים', 'אקריל', 'UV', 'nails', 'OPI'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'beautician',
    he: 'קוסמטיקאית',
    en: 'Beautician',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['טיפול פנים', 'הסרת שיער', 'פילינג', 'איפור קבוע', 'חבילת טיפולים'],
    expense_subs: ['קרמים וחומרים', 'מכשור (לייזר/IPL)', 'שכ״ד למכון', 'השתלמויות', 'ביטוח מקצועי'],
    keywords_boost: ['קוסמטיקה', 'טיפול פנים', 'פילינג', 'לייזר', 'IPL', 'בוטוקס', 'מילוי', 'beautician', 'facial'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'masseur',
    he: 'מעסה',
    en: 'Massage Therapist',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['עיסוי רפואי', 'עיסוי שוודי', 'עיסוי תאילנדי', 'חבילת עיסויים', 'ביקור בית'],
    expense_subs: ['שמני עיסוי', 'מיטת טיפול', 'שכ״ד / חלל משותף', 'מגבות', 'השתלמויות'],
    keywords_boost: ['עיסוי', 'שיאצו', 'עמוד שדרה', 'תאילנדי', 'שוודי', 'שמן', 'massage', 'spa'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'personal_trainer',
    he: 'מאמן כושר אישי',
    en: 'Personal Trainer',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['אימון אישי', 'חבילת אימונים', 'תוכנית תזונה', 'אימון אונליין', 'אימון קבוצתי'],
    expense_subs: ['ציוד אימון', 'מנוי לחדר כושר', 'ביגוד ספורט', 'תוכנת מעקב', 'הסמכות', 'דלק/רכב'],
    keywords_boost: ['אימון אישי', 'כושר', 'tabata', 'crossfit', 'מאמן', 'חדר כושר', 'fitness', 'workout', 'trainer'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'yoga_pilates',
    he: 'מורה ליוגה/פילאטיס',
    en: 'Yoga/Pilates Instructor',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['שיעור פרטי', 'שיעור קבוצתי', 'מנוי חודשי', 'סדנה', 'אונליין'],
    expense_subs: ['ציוד (מזרנים/רצועות)', 'שכ״ד לסטודיו', 'מנוי Zoom', 'הסמכות', 'ביטוח מקצועי'],
    keywords_boost: ['יוגה', 'פילאטיס', 'אסטנגה', 'ויניאסה', 'מדיטציה', 'יוגה', 'סטודיו', 'yoga', 'pilates'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'dog_walker',
    he: 'מטייל כלבים',
    en: 'Dog Walker',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['טיול בודד', 'מנוי חודשי', 'פנסיון יומי', 'אילוף'],
    expense_subs: ['רצועות וקולרים', 'שקיות איסוף', 'דלק/רכב עבודה', 'ביטוח עסק', 'שיווק'],
    keywords_boost: ['כלב', 'טיול', 'דוגי', 'אילוף', 'פנסיון כלבים', 'רצועה', 'dog walker', 'pet'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'cleaning_service',
    he: 'מנקה/אישת ניקיון',
    en: 'Cleaning Service',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['ניקיון בית', 'ניקיון משרד', 'ניקיון לאחר שיפוץ', 'מנוי חודשי'],
    expense_subs: ['חומרי ניקיון', 'כלי ניקיון', 'דלק/רכב', 'ביטוח עסק'],
    keywords_boost: ['ניקיון', 'מנקה', 'דירה', 'משרד', 'ספונג׳ה', 'חומרי ניקוי', 'cleaning'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'retail_owner',
    he: 'בעל חנות',
    en: 'Retail Store Owner',
    category: 'retail_service',
    vat: 'employer',
    income_subs: ['מכירות בחנות', 'מכירות אונליין', 'משלוחים', 'מתנות לעסקים'],
    expense_subs: ['רכש סחורה', 'שכ״ד', 'משכורות', 'חשמל ומים', 'תוכנת POS', 'אריזות', 'שיווק', 'ביטוח עסק', 'רואה חשבון'],
    keywords_boost: ['חנות', 'מלאי', 'POS', 'קופה', 'משלוח', 'אונליין', 'shopify', 'retail', 'store'],
    template_extras: ['inventory', 'open_invoices'],
  },
  {
    id: 'event_planner',
    he: 'מפיק אירועים',
    en: 'Event Planner',
    category: 'retail_service',
    vat: 'osek_morshe',
    income_subs: ['חתונה', 'בר/בת מצווה', 'אירוע עסקי', 'אירוע פרטי', 'מקדמה'],
    expense_subs: ['קייטרינג', 'תפאורה', 'הגברה ותאורה', 'צוות באירוע', 'שיווק', 'דלק/רכב', 'רואה חשבון'],
    keywords_boost: ['חתונה', 'בר מצווה', 'הפקה', 'אולם', 'תפאורה', 'הגברה', 'אירוע', 'event', 'wedding'],
    template_extras: ['cash_flow_per_project', 'open_invoices'],
  },
  {
    id: 'wedding_dj',
    he: 'די.ג׳יי לאירועים',
    en: 'Event DJ',
    category: 'retail_service',
    vat: 'osek_patur',
    income_subs: ['חתונה', 'בר/בת מצווה', 'מסיבה פרטית', 'אירוע עסקי', 'מקדמה'],
    expense_subs: ['ציוד הגברה', 'מחשב/בקרים', 'מנוי Beatport', 'דלק/רכב עבודה', 'ביטוח ציוד'],
    keywords_boost: ['DJ', 'הגברה', 'תקליטים', 'pioneer', 'serato', 'rekordbox', 'אירוע', 'מסיבה'],
    template_extras: ['mileage_log', 'gear_depreciation'],
  },

  // ============================================================
  // CREATIVE (צלמים, מעצבים, קופירייטרים, מוזיקאים)
  // ============================================================
  {
    id: 'photographer',
    he: 'צלם',
    en: 'Photographer',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['חתונות', 'בר/בת מצווה', 'צילומי משפחה', 'צילומי מוצר', 'תמונות סטוק', 'מקדמה'],
    expense_subs: ['מצלמה ועדשות', 'תאורה', 'דיסקים קשיחים', 'מנוי Lightroom', 'אתר/פורטפוליו', 'דלק/רכב עבודה', 'ביטוח ציוד'],
    keywords_boost: ['מצלמה', 'עדשה', 'sony', 'canon', 'nikon', 'lightroom', 'photoshop', 'צילום', 'photography'],
    template_extras: ['gear_depreciation', 'cash_flow_per_project'],
  },
  {
    id: 'videographer',
    he: 'צלם וידאו',
    en: 'Videographer',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['צילום אירוע', 'סרטון תדמית', 'פרסומת', 'עריכת וידאו', 'מקדמה'],
    expense_subs: ['מצלמת וידאו', 'מיקרופונים', 'גימבל', 'דיסקים', 'מנוי Adobe Premiere/DaVinci', 'דלק/רכב', 'ביטוח ציוד'],
    keywords_boost: ['וידאו', 'גימבל', 'sony fx', 'a7s', 'premiere', 'davinci', 'תדמית', 'video', 'edit'],
    template_extras: ['gear_depreciation', 'cash_flow_per_project'],
  },
  {
    id: 'graphic_designer',
    he: 'מעצב גרפי',
    en: 'Graphic Designer',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['לוגו ומיתוג', 'עיצוב לסושיאל', 'הזמנות וכרטיסים', 'אריזות', 'ריטיינר'],
    expense_subs: ['Adobe Creative Cloud', 'גופנים', 'תמונות סטוק', 'מחשב/מסך', 'הסמכות', 'אינטרנט עסקי'],
    keywords_boost: ['photoshop', 'illustrator', 'indesign', 'adobe', 'לוגו', 'מיתוג', 'גופן', 'figma', 'graphic'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'copywriter',
    he: 'קופירייטר',
    en: 'Copywriter',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['קופי לאתר', 'תוכן לסושיאל', 'ניוזלטר', 'תסריט פרסומת', 'ריטיינר'],
    expense_subs: ['ChatGPT Plus', 'Grammarly', 'מנוי לכלי SEO', 'מחשב', 'קוורקינג', 'אינטרנט עסקי'],
    keywords_boost: ['קופי', 'תוכן שיווקי', 'ניוזלטר', 'תסריט', 'CTA', 'sales page', 'ChatGPT', 'copywriting'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'content_writer',
    he: 'כותב תוכן',
    en: 'Content Writer',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['מאמר לבלוג', 'תוכן לאתר', 'תוכן לסושיאל', 'מדריך מעמיק', 'ריטיינר'],
    expense_subs: ['מנוי ChatGPT', 'מנוי לכלי SEO (Ahrefs/SemRush)', 'מנוי Grammarly', 'מחשב', 'אינטרנט עסקי'],
    keywords_boost: ['SEO', 'בלוג', 'מאמר', 'תוכן', 'ahrefs', 'semrush', 'keywords', 'content marketing'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'musician',
    he: 'מוזיקאי',
    en: 'Musician',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['הופעה חיה', 'הקלטות סטודיו', 'תמלוגים (אקו״ם)', 'מקדמה', 'מכירת מוזיקה'],
    expense_subs: ['כלי נגינה', 'מיתרים ואביזרים', 'הקלטות בסטודיו', 'שכ״ד לחזרות', 'נסיעות להופעות', 'אקו״ם', 'ביטוח ציוד'],
    keywords_boost: ['גיטרה', 'הופעה', 'סטודיו', 'אקו״ם', 'מיתר', 'מיקרופון', 'הקלטה', 'musician', 'gig'],
    template_extras: ['gear_depreciation', 'mileage_log'],
  },
  {
    id: 'music_producer',
    he: 'מפיק מוזיקלי',
    en: 'Music Producer',
    category: 'creative',
    vat: 'osek_morshe',
    income_subs: ['הפקת אלבום', 'מיקס ומאסטר', 'תמלוגים', 'מקדמה'],
    expense_subs: ['ציוד אולפן', 'מיקרופונים יוקרתיים', 'מנוי Pro Tools/Logic', 'פלאגינים', 'שכ״ד לאולפן', 'אקו״ם'],
    keywords_boost: ['pro tools', 'logic', 'ableton', 'מיקס', 'מאסטר', 'הפקה', 'plugin', 'studio', 'producer'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'visual_artist',
    he: 'אומנית פלסטית',
    en: 'Visual Artist',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['מכירת עבודה', 'תערוכה', 'הזמנה אישית', 'הדפסים', 'הוראה'],
    expense_subs: ['חומרי אומנות', 'מסגרות', 'שכ״ד לסטודיו', 'תערוכה (קטלוג/הקמה)', 'אתר תיק עבודות'],
    keywords_boost: ['ציור', 'פיסול', 'תערוכה', 'גלריה', 'אקריליק', 'שמן', 'בד ציור', 'artist', 'exhibition'],
    template_extras: ['inventory'],
  },
  {
    id: 'ceramicist',
    he: 'קרמיקאי',
    en: 'Ceramicist',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['מכירת כלים', 'סדנת קרמיקה', 'הזמנה אישית', 'יריד', 'אונליין (Etsy)'],
    expense_subs: ['חימר וגלזורות', 'תנור קרמיקה', 'אובניים', 'שכ״ד לסדנה', 'חשמל'],
    keywords_boost: ['חימר', 'אובניים', 'גלזורה', 'קרמיקה', 'תנור קרמי', 'pottery', 'ceramic', 'etsy'],
    template_extras: ['inventory'],
  },
  {
    id: 'jewelry_maker',
    he: 'מעצבת תכשיטים',
    en: 'Jewelry Designer',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['מכירה אונליין', 'יריד', 'הזמנה אישית', 'סיטונאי לחנויות', 'תיקון תכשיט'],
    expense_subs: ['מתכות יקרות', 'אבנים חצי יקרות', 'כלים', 'אריזה ומשלוח', 'שיווק אינסטגרם', 'אתר מכירות'],
    keywords_boost: ['תכשיט', 'זהב', 'כסף 925', 'יהלום', 'אבן חן', 'שרשרת', 'טבעת', 'jewelry', 'silver'],
    template_extras: ['inventory'],
  },
  {
    id: 'fashion_designer',
    he: 'מעצב אופנה',
    en: 'Fashion Designer',
    category: 'creative',
    vat: 'osek_morshe',
    income_subs: ['מכירת קולקציה', 'הזמנה אישית', 'סיטונאי לחנויות', 'שיתוף פעולה (מותג)'],
    expense_subs: ['בדים', 'תפירה ואטליה', 'הדפסות', 'שיווק/אינסטגרם', 'אריזה', 'שכ״ד לסטודיו'],
    keywords_boost: ['בד', 'תפירה', 'קולקציה', 'אופנה', 'תופרת', 'אטליה', 'fashion', 'collection'],
    template_extras: ['inventory', 'cash_flow_per_project'],
  },
  {
    id: 'illustrator',
    he: 'מאיירת',
    en: 'Illustrator',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['איור לספר', 'איור למגזין', 'הזמנה אישית', 'הדפסים', 'תמלוגי ספר'],
    expense_subs: ['Procreate / Adobe', 'iPad ועיפרון', 'הדפסות', 'אתר תיק עבודות', 'משלוח הדפסים'],
    keywords_boost: ['איור', 'procreate', 'ipad', 'ספר ילדים', 'חוברת', 'דמות', 'illustration', 'drawing'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'social_media_manager',
    he: 'מנהל סושיאל',
    en: 'Social Media Manager',
    category: 'creative',
    vat: 'osek_patur',
    income_subs: ['ניהול דף', 'יצירת תוכן', 'קמפיין ממומן', 'ייעוץ', 'ריטיינר'],
    expense_subs: ['Canva Pro', 'מנוי Later/Buffer', 'מנוי Meta Business', 'ChatGPT Plus', 'הסמכות שיווק'],
    keywords_boost: ['instagram', 'facebook', 'tiktok', 'reels', 'canva', 'meta ads', 'community', 'social media'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'influencer',
    he: 'יוצר/ת תוכן',
    en: 'Content Creator / Influencer',
    category: 'creative',
    vat: 'osek_morshe',
    income_subs: ['שיתוף פעולה ממומן', 'הכנסות YouTube', 'הכנסות TikTok', 'מכירת קורס', 'אפיליאייט'],
    expense_subs: ['מצלמה וציוד', 'תאורה', 'עריכת וידאו', 'מנוי כלי תוכן', 'שיווק', 'רואה חשבון', 'דלק/רכב'],
    keywords_boost: ['youtube', 'tiktok', 'instagram', 'reel', 'מימון', 'sponsorship', 'אפיליאייט', 'influencer'],
    template_extras: ['gear_depreciation', 'multi_currency'],
  },

  // ============================================================
  // EDUCATION (מורים פרטיים, מחנכים, מרצים)
  // ============================================================
  {
    id: 'teacher_public',
    he: 'מורה בבית ספר',
    en: 'Public School Teacher',
    category: 'education',
    vat: 'employee',
    income_subs: ['משכורת', 'תוספת שעות', 'גמולים (השתלמות/ייעוץ)', 'מענק יובל', 'תוספת חינוך'],
    expense_subs: ['ספרי לימוד', 'ציוד לכיתה', 'השתלמויות', 'הסתדרות המורים', 'נסיעות לעבודה'],
    keywords_boost: ['בית ספר', 'מורה', 'הסת״מ', 'משרד החינוך', 'גמול השתלמות', 'תלמיד', 'school teacher'],
  },
  {
    id: 'private_tutor',
    he: 'מורה פרטי',
    en: 'Private Tutor',
    category: 'education',
    vat: 'osek_patur',
    income_subs: ['שיעור פרטי', 'חבילת שיעורים', 'ליווי לבגרות', 'שיעור אונליין', 'מקדמה'],
    expense_subs: ['ספרי לימוד', 'אינטרנט עסקי', 'רישיון Zoom', 'חוגי השתלמות', 'דלק/רכב'],
    keywords_boost: ['שיעור פרטי', 'בגרות', '5 יחידות', 'מתמטיקה', 'אנגלית', 'פיזיקה', 'zoom', 'tutor'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'lecturer',
    he: 'מרצה',
    en: 'Lecturer',
    category: 'education',
    vat: 'osek_patur',
    income_subs: ['הרצאה חד פעמית', 'קורס סמסטריאלי', 'סדנה לארגון', 'ייעוץ אקדמי', 'מאמר'],
    expense_subs: ['ספרים מקצועיים', 'מנוי לכתבי עת', 'נסיעות', 'מחשב נייד', 'אינטרנט עסקי'],
    keywords_boost: ['הרצאה', 'אוניברסיטה', 'מכללה', 'סמסטר', 'מצגת', 'אקדמיה', 'professor', 'lecture'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'kindergarten_owner',
    he: 'בעלת גן ילדים',
    en: 'Kindergarten Owner',
    category: 'education',
    vat: 'employer',
    income_subs: ['שכר לימוד חודשי', 'דמי הרשמה', 'אגרת קייטנה', 'ארוחות'],
    expense_subs: ['משכורות סייעות', 'מזון לילדים', 'שכ״ד מבנה', 'ביטוח גן', 'ציוד וצעצועים', 'אגרות רישוי', 'רואה חשבון', 'תוכנת ניהול גן'],
    keywords_boost: ['גן ילדים', 'משרד החינוך', 'סייעת', 'פעוטון', 'מעון', 'הרשמה', 'kindergarten', 'daycare'],
    template_extras: ['recurring_clients', 'open_invoices'],
  },
  {
    id: 'nanny',
    he: 'מטפלת',
    en: 'Nanny',
    category: 'education',
    vat: 'employee',
    income_subs: ['שכר חודשי', 'שעות נוספות', 'תוספת חג', 'מענק'],
    expense_subs: ['נסיעות לעבודה', 'חומרי יצירה', 'אוכל לעבודה'],
    keywords_boost: ['מטפלת', 'תינוק', 'פעוט', 'גן', 'משחקייה', 'בייביסיטר', 'nanny', 'babysitter'],
  },
  {
    id: 'hobby_instructor',
    he: 'מורה לחוגים',
    en: 'Hobby Class Instructor',
    category: 'education',
    vat: 'osek_patur',
    income_subs: ['חוג שבועי', 'חוג קיץ', 'סדנה חד פעמית', 'יום הולדת', 'מנוי'],
    expense_subs: ['חומרי יצירה', 'ציוד', 'שכ״ד לחלל', 'שיווק להורים', 'דלק/רכב'],
    keywords_boost: ['חוג', 'יצירה', 'יום הולדת', 'מתנ״ס', 'אומנות', 'בישול', 'קרמיקה', 'workshop'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'music_teacher',
    he: 'מורה למוזיקה',
    en: 'Music Teacher',
    category: 'education',
    vat: 'osek_patur',
    income_subs: ['שיעור פרטי', 'חבילת שיעורים', 'הכנה לקונסרבטוריון', 'הופעה עם תלמידים'],
    expense_subs: ['ספרי תווים', 'תיקון כלי נגינה', 'מטרונום ואביזרים', 'דלק/רכב', 'שכ״ד לחדר חזרות'],
    keywords_boost: ['פסנתר', 'גיטרה', 'תווים', 'סולפז׳', 'קונסרבטוריון', 'תיאוריה מוזיקלית', 'music lesson'],
    template_extras: ['recurring_clients'],
  },
  {
    id: 'driving_instructor',
    he: 'מורה לנהיגה',
    en: 'Driving Instructor',
    category: 'education',
    vat: 'osek_morshe',
    income_subs: ['שיעור נהיגה', 'מבחן פנימי', 'ליווי לטסט', 'חבילת שיעורים'],
    expense_subs: ['דלק', 'תחזוקת רכב לימוד', 'ביטוח רכב לימוד', 'רישוי רכב', 'רישיון מורה', 'אגרת טסט (אם משלם בשמו)'],
    keywords_boost: ['נהיגה', 'טסט', 'רישיון', 'מורה לנהיגה', 'רכב לימוד', 'משרד הרישוי', 'driving instructor'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'coach',
    he: 'מאמן אישי (לייף קואצ׳)',
    en: 'Life Coach',
    category: 'education',
    vat: 'osek_patur',
    income_subs: ['פגישה אישית', 'תוכנית אימון', 'סדנה קבוצתית', 'אימון אונליין', 'הרצאה'],
    expense_subs: ['הסמכות (ICF)', 'השתלמויות', 'CRM', 'שיווק / קמפיינים', 'שכ״ד לפגישות', 'רישיון Zoom'],
    keywords_boost: ['קואצ׳ינג', 'NLP', 'ICF', 'מטרות', 'אימון אישי', 'התפתחות אישית', 'coaching', 'mindset'],
    template_extras: ['recurring_clients'],
  },

  // ============================================================
  // LOGISTICS (נהגי משאית, שליחים, מובילים, ימאים)
  // ============================================================
  {
    id: 'truck_driver',
    he: 'נהג משאית',
    en: 'Truck Driver',
    category: 'logistics',
    vat: 'osek_morshe',
    income_subs: ['הובלה לפי נסיעה', 'הובלה לפי שעה', 'הובלת לילה', 'נסיעות ארוכות', 'בונוס דחיפות'],
    expense_subs: ['דלק/סולר', 'תחזוקת משאית', 'ביטוח משאית', 'אגרת אילון/כביש 6', 'חניות', 'רישוי משאית', 'טכוגרף', 'רואה חשבון'],
    keywords_boost: ['משאית', 'הובלה', 'סולר', 'נסיעת לילה', 'טכוגרף', 'כביש 6', 'truck', 'freight'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'taxi_driver',
    he: 'נהג מונית',
    en: 'Taxi Driver',
    category: 'logistics',
    vat: 'osek_patur',
    income_subs: ['נסיעות', 'עמלת gett', 'יום עמוס', 'נסיעה לשדה תעופה', 'מזומן'],
    expense_subs: ['דלק', 'ביטוח רכב מונית', 'רישוי מונית', 'תחזוקה רגילה', 'תחזוקה שוטפת (תקלות)', 'חניות', 'תיקון רכב'],
    keywords_boost: ['מונית', 'gett', 'נתב״ג', 'נסיעה', 'נהג', 'תעריף', 'דלק', 'taxi', 'cab'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'rideshare_driver',
    he: 'נהג Yango/Bolt',
    en: 'Rideshare Driver',
    category: 'logistics',
    vat: 'osek_patur',
    income_subs: ['נסיעות באפליקציה', 'בונוסים', 'מזומן', 'עומס שעת שיא'],
    expense_subs: ['דלק', 'ביטוח רכב', 'תחזוקת רכב', 'רישוי רכב', 'עמלת אפליקציה', 'ניקוי רכב'],
    keywords_boost: ['yango', 'bolt', 'נסיעה', 'אפליקציה', 'בונוס', 'עומס', 'rideshare', 'gig driver'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'delivery_courier',
    he: 'שליח',
    en: 'Delivery Courier',
    category: 'logistics',
    vat: 'osek_patur',
    income_subs: ['משלוח Wolt/10bis', 'שליחויות עסקיות', 'בונוס', 'חבילות'],
    expense_subs: ['דלק (קטנוע/אופניים חשמליים)', 'תחזוקת קטנוע', 'ביטוח רכב דו גלגלי', 'קסדה ובגדי בטיחות', 'תיק שליח'],
    keywords_boost: ['wolt', 'משלוח', '10bis', 'שליח', 'קטנוע', 'אופניים חשמליים', 'delivery', 'courier'],
    template_extras: ['mileage_log'],
  },
  {
    id: 'forklift_operator',
    he: 'נהג מלגזה',
    en: 'Forklift Operator',
    category: 'logistics',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'תוספת לילה', 'בונוס'],
    expense_subs: ['רישיון מלגזה', 'נעלי עבודה', 'נסיעות לעבודה'],
    keywords_boost: ['מלגזה', 'מחסן', 'משטח', 'הרמה', 'יבוא', 'forklift', 'warehouse'],
  },
  {
    id: 'warehouse_worker',
    he: 'עובד מחסן',
    en: 'Warehouse Worker',
    category: 'logistics',
    vat: 'employee',
    income_subs: ['שכר שעתי', 'שעות נוספות', 'משמרת לילה', 'בונוס סוף שנה'],
    expense_subs: ['נסיעות לעבודה', 'נעלי עבודה', 'בגדי עבודה', 'אוכל בעבודה'],
    keywords_boost: ['מחסן', 'משמרת', 'ליקוט', 'חבילות', 'amazon', 'logistics', 'warehouse'],
  },
  {
    id: 'sailor',
    he: 'ימאי',
    en: 'Sailor',
    category: 'logistics',
    vat: 'employee',
    income_subs: ['משכורת', 'דמי הפלגה', 'מענק לילה', 'בונוס סיום הפלגה'],
    expense_subs: ['ביטוח ימי', 'הסמכות ימיות', 'חופשת קרקע', 'נסיעות לנמל'],
    keywords_boost: ['אונייה', 'נמל', 'הפלגה', 'צים', 'ימאי', 'דק', 'ship', 'maritime', 'sailor'],
  },
  {
    id: 'logistics_manager',
    he: 'מנהל לוגיסטיקה',
    en: 'Logistics Manager',
    category: 'logistics',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס שנתי', 'אופציות', 'תוספת רכב'],
    expense_subs: ['נסיעות לעבודה', 'קורסי לוגיסטיקה', 'ביטוח רפואי משלים', 'כנסים'],
    keywords_boost: ['לוגיסטיקה', 'שרשרת אספקה', 'יבוא', 'יצוא', 'SAP', 'WMS', 'מחסן', 'supply chain'],
  },

  // ============================================================
  // AGRICULTURE (חקלאים, מגדלים, רפתנים, גננים)
  // ============================================================
  {
    id: 'farmer',
    he: 'חקלאי',
    en: 'Farmer',
    category: 'agriculture',
    vat: 'osek_morshe',
    income_subs: ['מכירת יבול לסיטונאי', 'מכירה ישירה (יריד)', 'יצוא', 'תמיכה ממשרד החקלאות', 'דמי חכירה'],
    expense_subs: ['זרעים ושתילים', 'דשנים וחומרי הדברה', 'דלק/סולר', 'תחזוקת טרקטור', 'שכר עובדים זרים', 'מים לחקלאות', 'ביטוח חקלאי', 'רואה חשבון'],
    keywords_boost: ['יבול', 'שדה', 'טרקטור', 'דשן', 'הדברה', 'משרד החקלאות', 'מים לחקלאות', 'farmer', 'crop'],
    template_extras: ['cash_flow_per_project'],
  },
  {
    id: 'orchard_grower',
    he: 'מגדל פירות',
    en: 'Orchard Grower',
    category: 'agriculture',
    vat: 'osek_morshe',
    income_subs: ['מכירה לסיטונאי', 'יצוא', 'מכירה ישירה', 'תמיכה ממשרד החקלאות'],
    expense_subs: ['שתילים', 'דשנים', 'הגנת הצומח', 'מים', 'קטיף (עובדים זרים)', 'אריזה', 'שינוע', 'ביטוח'],
    keywords_boost: ['מטע', 'פרי', 'תפוח', 'אבוקדו', 'הדרים', 'קטיף', 'אריזה', 'orchard', 'fruit'],
    template_extras: ['inventory'],
  },
  {
    id: 'dairy_farmer',
    he: 'רפתן',
    en: 'Dairy Farmer',
    category: 'agriculture',
    vat: 'osek_morshe',
    income_subs: ['מכירת חלב לתנובה/טרה', 'מכירת עגלים', 'תמיכה ממועצת החלב', 'גבינות לשוק'],
    expense_subs: ['מזון לבקר', 'וטרינר ותרופות', 'תחזוקת רפת', 'מערכת חליבה', 'דלק', 'עובדים', 'ביטוח'],
    keywords_boost: ['רפת', 'פרה', 'חלב', 'תנובה', 'מועצת החלב', 'חליבה', 'עגל', 'dairy', 'cow'],
    template_extras: ['inventory'],
  },
  {
    id: 'chicken_farmer',
    he: 'מגדל עופות',
    en: 'Poultry Farmer',
    category: 'agriculture',
    vat: 'osek_morshe',
    income_subs: ['מכירת ביצים', 'מכירת עופות לבשר', 'תמיכת מועצת הלול'],
    expense_subs: ['מזון לעופות', 'אפרוחים', 'וטרינר', 'תחזוקת לולים', 'חשמל וחימום', 'עובדים', 'אריזה'],
    keywords_boost: ['לול', 'תרנגולת', 'ביצים', 'אפרוח', 'תפזורת', 'מועצת הלול', 'poultry', 'chicken'],
    template_extras: ['inventory'],
  },
  {
    id: 'beekeeper',
    he: 'דבוראי',
    en: 'Beekeeper',
    category: 'agriculture',
    vat: 'osek_patur',
    income_subs: ['מכירת דבש', 'השכרת כוורות להאבקה', 'דונג ונרות', 'יריד'],
    expense_subs: ['כוורות וציוד', 'לבוש מגן', 'מזון לדבורים בחורף', 'טיפול נגד מחלות', 'תחבורה'],
    keywords_boost: ['דבש', 'דבורים', 'כוורת', 'מועצת הדבש', 'האבקה', 'דונג', 'honey', 'bee'],
    template_extras: ['inventory'],
  },
  {
    id: 'florist',
    he: 'פרחנית',
    en: 'Florist',
    category: 'agriculture',
    vat: 'osek_patur',
    income_subs: ['זרי פרחים', 'אירועים (חתונה/אזכרה)', 'משלוחים', 'מכירה בחנות'],
    expense_subs: ['פרחים מהשוק', 'אגרטלים ואריזה', 'שכ״ד לחנות', 'מקרר פרחים', 'דלק למשלוחים', 'ביטוח'],
    keywords_boost: ['פרחים', 'זר', 'חתונה', 'אזכרה', 'משלוח', 'אגרטל', 'florist', 'bouquet'],
    template_extras: ['inventory'],
  },

  // ============================================================
  // EMPLOYEE (שכירים רגילים — אין קשר לעסק עצמאי)
  // ============================================================
  {
    id: 'office_worker',
    he: 'עובד משרד',
    en: 'Office Worker',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'בונוס שנתי', 'החזרי נסיעות'],
    expense_subs: ['נסיעות לעבודה', 'אוכל בעבודה', 'ביגוד', 'ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)'],
    keywords_boost: ['משכורת', 'משרד', 'תלוש', 'ביטוח לאומי', 'מס הכנסה', 'קרן השתלמות', 'office', 'salary'],
  },
  {
    id: 'civil_servant',
    he: 'עובד מדינה',
    en: 'Civil Servant',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'תוספת ותק', 'דרגה', 'מענק יובל', 'שעות נוספות'],
    expense_subs: ['נסיעות לעבודה', 'אגודות מקצועיות', 'ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)'],
    keywords_boost: ['משרד ממשלתי', 'הסת״ע', 'דרגה', 'דירוג', 'נציבות שירות המדינה', 'civil servant', 'gov'],
  },
  {
    id: 'security_guard',
    he: 'מאבטח / שומר',
    en: 'Security Guard',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'משמרת לילה', 'שעות נוספות', 'תוספת חג', 'בונוס'],
    expense_subs: ['נסיעות לעבודה', 'נעלי עבודה', 'מדים', 'הסמכות (אקדח/2)'],
    keywords_boost: ['שומר', 'מאבטח', 'משמרת לילה', 'אבטחה', 'מודיעין אזרחי', 'guard', 'security'],
  },
  {
    id: 'soldier',
    he: 'חייל בקבע',
    en: 'Career Soldier (IDF)',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'תוספת קבע', 'מענק שחרור', 'תוספת תפקיד', 'תוספת תורנות'],
    expense_subs: ['נסיעות', 'מדים נוספים', 'מועדון הקצינים', 'קרן השתלמות (חלק עובד)'],
    keywords_boost: ['צה״ל', 'קבע', 'דרגה', 'מילואים', 'שחרור', 'בסיס', 'IDF', 'army'],
  },
  {
    id: 'police_officer',
    he: 'שוטר',
    en: 'Police Officer',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'תורנויות', 'תוספת תפקיד', 'מענק יובל'],
    expense_subs: ['נסיעות', 'מדים', 'איגוד השוטרים', 'קרן השתלמות (חלק עובד)'],
    keywords_boost: ['משטרה', 'שוטר', 'תחנה', 'תורנות', 'יחידה', 'police', 'officer'],
  },
  {
    id: 'firefighter',
    he: 'כבאי',
    en: 'Firefighter',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'תורנויות', 'תוספת סיכון', 'מענק יובל'],
    expense_subs: ['נסיעות', 'מדים', 'איגוד הכבאים', 'הסמכות'],
    keywords_boost: ['כבאות', 'כבאי', 'הצלה', 'מטף', 'תורנות', 'firefighter', 'rescue'],
  },
  {
    id: 'flight_attendant',
    he: 'דייל/ת',
    en: 'Flight Attendant',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות טיסה', 'דמי שהייה (per diem)', 'דיוטי פרי', 'בונוס'],
    expense_subs: ['מדים', 'ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'נסיעות לנתב״ג'],
    keywords_boost: ['אל על', 'נתב״ג', 'טיסה', 'דייל', 'דיילת', 'per diem', 'דיוטי פרי', 'flight attendant'],
    template_extras: ['multi_currency'],
  },
  {
    id: 'pilot',
    he: 'טייס מסחרי',
    en: 'Commercial Pilot',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות טיסה', 'דמי שהייה', 'תוספת מפקד', 'בונוס'],
    expense_subs: ['רישיון טייס (חידוש)', 'בדיקות רפואיות', 'מדים', 'איגוד הטייסים', 'נסיעות'],
    keywords_boost: ['טייס', 'אל על', 'בואינג', 'איירבוס', 'קוקפיט', 'שעות טיסה', 'pilot', 'aviation'],
    template_extras: ['multi_currency'],
  },
  {
    id: 'salesperson_employed',
    he: 'איש מכירות (שכיר)',
    en: 'Sales (Employee)',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת בסיס', 'עמלות מכירה', 'בונוס יעדים', 'תוספת רכב', 'אש״ל'],
    expense_subs: ['דלק לרכב חברה (הטבה)', 'אוכל פגישות', 'ביגוד', 'ביטוח רפואי משלים'],
    keywords_boost: ['מכירות', 'עמלה', 'יעד', 'CRM', 'salesforce', 'לקוח', 'sales', 'commission'],
    template_extras: ['commission_split'],
  },
  {
    id: 'manager_employed',
    he: 'מנהל בארגון',
    en: 'Manager (Employee)',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'בונוס שנתי', 'אופציות (RSU)', 'תוספת רכב', 'מענק חתימה'],
    expense_subs: ['נסיעות לעבודה', 'ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)', 'כנסים', 'הסמכות מנהיגות'],
    keywords_boost: ['מנכ״ל', 'סמנכ״ל', 'מנהל', 'דירקטוריון', 'אופציות', 'RSU', 'manager', 'executive'],
  },
  {
    id: 'retiree',
    he: 'גמלאי/ת',
    en: 'Retiree',
    category: 'employee',
    vat: 'employee',
    income_subs: ['קצבת זיקנה (בט״ל)', 'קצבת פנסיה', 'קרן השתלמות (משיכה)', 'גמל (משיכה)', 'הכנסה מנכס'],
    expense_subs: ['ביטוח בריאות משלים', 'תרופות', 'מגורים', 'נסיעות וטיולים', 'משפחה ונכדים'],
    keywords_boost: ['פנסיה', 'גמל', 'קצבה', 'ביטוח לאומי', 'זיקנה', 'גמלאי', 'pension', 'retired'],
  },
  {
    id: 'student',
    he: 'סטודנט/ית',
    en: 'Student',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת מעבודה', 'מלגה', 'הלוואת לימודים', 'עזרה מההורים', 'פיצויי שחרור'],
    expense_subs: ['שכר לימוד', 'דיור (שכר דירה)', 'ספרי לימוד', 'תחבורה ציבורית', 'מזון'],
    keywords_boost: ['אוניברסיטה', 'מכללה', 'שכ״ל', 'מלגה', 'הלוואת לימודים', 'מעונות', 'student', 'tuition'],
  },
  {
    id: 'unemployed',
    he: 'מובטל/ת',
    en: 'Job Seeker',
    category: 'employee',
    vat: 'employee',
    income_subs: ['דמי אבטלה', 'פיצויים', 'הכנסה זמנית', 'עזרה מהמשפחה'],
    expense_subs: ['הוצאות יומיומיות', 'תחבורה לראיונות', 'הסמכות / קורסים', 'ביטוח לאומי (אם לא עובד)'],
    keywords_boost: ['אבטלה', 'דמי אבטלה', 'לשכת תעסוקה', 'ראיון עבודה', 'פיצויים', 'unemployed', 'job seeker'],
  },
  {
    id: 'homemaker',
    he: 'הורה במשרה מלאה (לא עובד/ת)',
    en: 'Homemaker',
    category: 'employee',
    vat: 'employee',
    income_subs: ['קצבת ילדים', 'עזרה מבן/בת זוג', 'הכנסה מנכס', 'עזרה מההורים'],
    expense_subs: ['מזון לבית', 'ביגוד ילדים', 'חינוך וחוגים', 'בריאות', 'תחבורה'],
    keywords_boost: ['בית', 'ילדים', 'הורה', 'קצבת ילדים', 'משק בית', 'homemaker', 'parent'],
  },

  // ============================================================
  // GENERIC FALLBACK — when nothing else fits
  // ============================================================
  {
    id: 'other_freelance',
    he: 'עצמאי אחר',
    en: 'Other Freelancer',
    category: 'professional_services',
    vat: 'osek_patur',
    income_subs: ['תקבול מלקוח', 'מקדמה', 'תשלום סופי', 'מכירה אונליין', 'ייעוץ חד פעמי'],
    expense_subs: ['ציוד', 'תוכנות ומנויים', 'שיווק', 'דלק/רכב עבודה', 'אינטרנט עסקי', 'ביטוח עסק', 'רואה חשבון'],
    keywords_boost: ['חשבונית', 'לקוח', 'תקבול', 'עצמאי', 'פרילנס', 'freelance', 'invoice'],
  },
  {
    id: 'other_employee',
    he: 'שכיר אחר',
    en: 'Other Employee',
    category: 'employee',
    vat: 'employee',
    income_subs: ['משכורת', 'שעות נוספות', 'בונוס', 'החזרי נסיעות', 'תוספת חג'],
    expense_subs: ['נסיעות לעבודה', 'אוכל בעבודה', 'ביגוד', 'ביטוח רפואי משלים', 'קרן השתלמות (חלק עובד)'],
    keywords_boost: ['משכורת', 'תלוש', 'שכיר', 'מעסיק', 'employee', 'salary'],
  },
];

// Lookup helpers --------------------------------------------------------

// Returns the profession entry with the given id, or null.
//   findProfession('plumber') -> { id: 'plumber', he: 'אינסטלטור', ... }
export function findProfession(id) {
  if (!id) return null;
  return PROFESSIONS.find(p => p.id === id) || null;
}

// Returns an object { categoryKey: [profession, ...] } grouping by category.
// Useful for rendering the onboarding dropdown grouped by section.
export function professionsByCategory() {
  const out = {};
  for (const p of PROFESSIONS) {
    if (!out[p.category]) out[p.category] = [];
    out[p.category].push(p);
  }
  return out;
}

// Sanity-check exports for tests / admin tooling.
export const PROFESSION_IDS = PROFESSIONS.map(p => p.id);
export const TOTAL_PROFESSIONS = PROFESSIONS.length;
export const CATEGORIES = [
  'construction',
  'professional_services',
  'healthcare',
  'tech',
  'retail_service',
  'creative',
  'education',
  'logistics',
  'agriculture',
  'employee',
];
